language: python

jobs:
  include:
    - stage: test
      python: 3.8
      addons:
        postgresql: "10"
        apt:
          packages:
          - postgresql-10
          - postgresql-client-10
      install:
        - pip install -r requirements.txt
      env: SECRET_KEY='Kf33^8fVAMsRW2d!@EMMMK@G5jRQXmQ!DBcax9V^jXPp9F3PFw' \
           ALLOWED_HOST='127.0.0.1' \
           APP_USER='' \
           APP_DB='' \
           APP_USER_PASSWORD='' \
           DB_HOST='127.0.0.1' \
           POSTGRES_PASSWORD='' \
           AUTH0_DOMAIN='domain.eu.auth0.com' \
           AUTH0_USERNAME='Auth0user' \
           AUTH0_EMAIL='username@domain.eu' \
           API_IDENTIFIER='https://api-name'
      script:
        - python manage.py test --parallel
