language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
install:
  - pip install -r requirements.txt
script:
  - python manage.py test --parallel
