# Generated by Django 2.2.6 on 2019-11-12 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='for_persons',
            new_name='servings',
        ),
    ]
