# Generated by Django 3.0.8 on 2020-07-17 09:24

from django.db import migrations
from django.conf import settings


def create_data(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    user = User(pk=1, username="auth0user", is_active=True , email="***REMOVED***")
    user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20191112_2234'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
