# Generated by Django 3.0.8 on 2020-08-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auth0user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['name']},
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plural', models.CharField(max_length=100)),
                ('recipes', models.ManyToManyField(to='recipes.Recipe')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
