# Generated by Django 3.0.8 on 2020-08-23 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20200821_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientamount',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='ingredientamount',
            name='unit',
        ),
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=4)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Unit')),
            ],
        ),
        migrations.AddField(
            model_name='ingredientamount',
            name='amount',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='recipes.Amount'),
        ),
    ]
